### ISSUE TITLE
Help with processors 

### ISSUE THREAD

**Issue by G4burieru** [Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE#3]
### Variant

None

### Control type

None

### Control mode

None

### Description

Hello, i'm a complete noob with firmware hack. I bought a motherboard YST-DXT-J20 V5.7, it has a mainboard and 2 side boards (not split boards), but the processor in the mainboard is a MM32, do you know if i can just buy a STM32F103RCT6 processor and switch with the MM32?

**Comment by Kambodia91** [comment]
Hello, the STM32 processor that I used in my project has different sizes and different pin connections.  First of all, I would check what specific MM32 model is in the board, if I find an STM32 model with the same pin out.  I would check which pin is responsible for what, where the input, output and control are, etc. And whether there is a programming connector.  As for hacking, it would be a simple matter if there was already an STM32 on the board.

**Comment by G4burieru** [comment]
Thanks for the response, there is something more that i have to worry when switching processors beside the pinout?

**Comment by Kambodia91** [comment]
All that remains is to map the pins on the board to match the outputs in the program, or modify them slightly because from what I noticed there are different connection configurations.  What processor is there originally?

**Comment by G4burieru** [comment]
Originally the processor was a MM32SPIN 0280DSP

**Comment by Kambodia91** [comment]
Can you take a photo of what it looks like?  if you have one motherboard and two side boards, this MM32 processor should support 2 wheels, and it should be larger than 48pin

**Comment by G4burieru** [comment]
![IMG_20231214_124917.jpg](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/103967434/1339e4a6-fe34-4239-8783-907979101307)

![IMG_20231214_124813.jpg](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/103967434/8c544684-5936-48bd-8b46-eeacbeb8bde6)

it looks like this

**Comment by Kambodia91** [comment]
Hey!  I did some searching on the Internet and found a [datasheet](https://crossic.com/wp-content/uploads/2021/12/DS_MM32SPIN0280_SC.pdf) of this processor, or rather its family.  Now you need to compare the pins with [stm32f103rct6](https://www.st.com/resource/en/datasheet/stm32f103re.pdf) with 64pin
MM32:
![Screenshot_2023-12-14-17-55-09-04_3aea4af51f236e4932235fdada7d1643](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/88535933/518b0836-71f0-4cf1-8a40-987dc966442d)
STM32:
![Screenshot_2023-12-14-18-02-18-41_3aea4af51f236e4932235fdada7d1643](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/88535933/fe865b7e-a718-43d6-8889-f614f3f41b5e)

They do not look identical, but it may not matter that much because the pins that are different may not be used, now you need to check on the board whether they are used for something.

**Comment by G4burieru** [comment]
i have looked the datasheets and the only pins that differ are the PD pins, on STM32 they are for Voltage but in the MM32 they are I/O pins, wouldn't that be a problem?

**Comment by Kambodia91** [comment]
Personally, I would leave these pins raised and not soldered, I looked into the [Eferu](https://github.com/EFeru/hoverboard-firmware-hack-FOC) software and the PD pins are not involved in the program, so there is a chance that it will work

**Comment by G4burieru** [comment]
one more question, on your project, the original processor had the PD pins instead the Vss's, Vdd's and Vbat similar to my case?

**Comment by Kambodia91** [comment]
Yes.  It was the same for me.  I soldered them.  I checked where the pins go.  and lead to the programmer connector.  3.3V and GND

**Comment by Kambodia91** [comment]
I found from the datashiet that the PD pins in this place are responsible for UART1 communication in MM32.

**Comment by G4burieru** [comment]
I didn't understand very well, did you solder the VDD, VSS and VBAT pins where the PD ones were?

**Comment by Kambodia91** [comment]
in my project, the output from the original MM32 PD3 and PD2 are connected to the chip programming connector.  VBAT is not used.

PD2 and PD3 as VCC, VDD uses STM32 as power supply for programming/debugging

**Comment by Kambodia91** [comment]
look what I have PD2 and PD3 connected to:
![IMG20221201034617](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/88535933/540c1cf0-cc7a-4152-9abc-ec62f6dd0ebd)

solder the programming connector
red - 3.3V
yellow - SWDIO
yellow - SWCLK
black - GND
![IMG20230102184358](https://github.com/Kambodia91/Hoverboard-firmware-hack-FOC-MASTER-SLAVE/assets/88535933/d3918bdc-2dc7-43f0-ba24-b474469523eb)

You need to check what these paths are connected to.
